### ISSUE TITLE
Unable to develop

### ISSUE THREAD

**Issue by ghost** [jlengstorf/livestream-gatsby-themes#1]
I used 'yarn workspace site develop' at 'livestream-gatsby-themes' and got this error......

************************************

λ yarn workspace site develop
yarn workspace v1.7.0
yarn run v1.7.0
$ gatsby develop
internal/modules/cjs/loader.js:550
    throw err;
    ^

Error: Cannot find module 'gatsby-cli'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:548:15)
    at Function.Module._load (internal/modules/cjs/loader.js:475:25)
    at Module.require (internal/modules/cjs/loader.js:598:17)
    at require (internal/modules/cjs/helpers.js:11:18)
    at Object.<anonymous> (C:\Users\doakh\Development\livestream-gatsby-themes\node_modules\gatsby\dist\bin\gatsby.js:4:1)
    at Module._compile (internal/modules/cjs/loader.js:654:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:665:10)
    at Module.load (internal/modules/cjs/loader.js:566:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:506:12)
    at Function.Module._load (internal/modules/cjs/loader.js:498:3)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
error Command failed.
Exit code: 1
Command: C:\Program Files\nodejs\node.exe
Arguments: C:\Program Files (x86)\Yarn\lib\cli.js develop
Directory: C:\Users\doakh\Development\livestream-gatsby-themes\site
Output:

info Visit https://yarnpkg.com/en/docs/cli/workspace for documentation about this command.

***************************************

I read that 'gatsby-cli' should be used, use a package.json script, which exists.
Windows 10 Pro

**Comment by johno** [comment]
Hey @doakheggeness have you run `yarn` in the root of the repo?

**Comment by ghost** [comment]
Yes, I ran `yarn` in the root 'livestream-gatsby-themes' and then I tried `yarn workspace site develop`. I would like to explore this, it sounds like a good idea.

**Comment by ghost** [comment]
Got it to work, thanks
